FROM ubuntu:18.04

RUN dpkg --add-architecture i386 \
  && apt-get update -qq \
  && apt-get install -qy libsdl2-dev:i386 gcc-multilib yasm git

RUN mkdir /output
VOLUME /output

COPY fetch+compile.sh /
RUN chmod +x /fetch+compile.sh

CMD ["/fetch+compile.sh"]
