FROM ubuntu:14.04

RUN dpkg --add-architecture i386 \
  && apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y yasm git \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y libsdl2-2.0-0:i386 libgles2-mesa-dev:i386 libglu1-mesa-dev:i386 libsdl2-dev:i386 \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-multilib

RUN mkdir /output
VOLUME /output

COPY fetch+compile.sh /
RUN chmod +x /fetch+compile.sh

CMD ["/fetch+compile.sh"]
