FROM ubuntu:22.04

RUN dpkg --add-architecture i386
RUN apt-get update -qq
RUN DEBIAN_FRONTEND=noninteractive apt-get install -o APT::Immediate-Configure=false -qy \
       libsdl2-dev:i386 gcc-multilib yasm git

RUN mkdir /output
VOLUME /output

COPY fetch+compile.sh /
RUN chmod +x /fetch+compile.sh

CMD ["/fetch+compile.sh"]
